"""initial schema

Revision ID: d5f3364d6b37
Revises: 
Create Date: 2026-08-25 16:28:52.968274
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd5f3364d6b37'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_Agents',
    sa.Column('agentId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AgentName', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('aadhar', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('agentId')
    )
    op.create_index(op.f('ix_t_Agents_AgentName'), 't_Agents', ['AgentName'], unique=False)
    op.create_table('t_Item',
    sa.Column('itemId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('manufactureYr', sa.DateTime(timezone=True), nullable=True),
    sa.Column('materialType', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('additionalParam1', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('qty >= 0', name='ck_item_qty_non_negative'),
    sa.PrimaryKeyConstraint('itemId')
    )
    op.create_index(op.f('ix_t_Item_name'), 't_Item', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('RentalPrice',
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=100), nullable=True),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('rentFrequency', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rent >= 0', name='ck_price_rent_non_negative'),
    sa.ForeignKeyConstraint(['itemId'], ['t_Item.itemId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itemId')
    )
    op.create_table('t_AvaiableStock',
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('RentedOutQty', sa.Integer(), nullable=False),
    sa.Column('availableQty', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('"RentedOutQty" >= 0', name='ck_stock_rented_non_negative'),
    sa.CheckConstraint('"availableQty" + "RentedOutQty" = qty', name='ck_stock_conservation'),
    sa.CheckConstraint('"availableQty" >= 0', name='ck_stock_available_non_negative'),
    sa.CheckConstraint('qty >= 0', name='ck_stock_qty_non_negative'),
    sa.ForeignKeyConstraint(['itemId'], ['t_Item.itemId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itemId')
    )
    op.create_table('t_party',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('aadhaar', sa.String(length=20), nullable=True),
    sa.Column('secondaryMobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('agentId', sa.Integer(), nullable=True),
    sa.Column('agentName', sa.String(length=100), nullable=True),
    sa.Column('siteAddress', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'payment_due', 'default', 'closed', name='party_status'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('activeItems', sa.Integer(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('"activeItems" >= 0', name='ck_party_active_items_non_negative'),
    sa.ForeignKeyConstraint(['agentId'], ['t_Agents.agentId'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_party_agentId'), 't_party', ['agentId'], unique=False)
    op.create_index(op.f('ix_t_party_mobile'), 't_party', ['mobile'], unique=False)
    op.create_index(op.f('ix_t_party_name'), 't_party', ['name'], unique=False)
    op.create_index(op.f('ix_t_party_status'), 't_party', ['status'], unique=False)
    op.create_table('rentalContract',
    sa.Column('contractId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contractNo', sa.String(length=30), nullable=False),
    sa.Column('partyId', sa.String(length=50), nullable=False),
    sa.Column('PartyName', sa.String(length=100), nullable=True),
    sa.Column('agentId', sa.Integer(), nullable=True),
    sa.Column('AgentName', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('open', 'partial', 'closed', 'cancelled', name='contract_status'), nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expectedReturnDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advancePaid', sa.Float(), nullable=False),
    sa.Column('accruedRent', sa.Float(), nullable=False),
    sa.Column('totalPaid', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"accruedRent" >= 0', name='ck_contract_accrued_non_negative'),
    sa.CheckConstraint('"advancePaid" >= 0', name='ck_contract_advance_non_negative'),
    sa.CheckConstraint('"totalPaid" >= 0', name='ck_contract_paid_non_negative'),
    sa.ForeignKeyConstraint(['agentId'], ['t_Agents.agentId'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partyId'], ['t_party.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contractId')
    )
    op.create_index('ix_contract_party_date', 'rentalContract', ['partyId', 'startDate'], unique=False)
    op.create_index(op.f('ix_rentalContract_contractNo'), 'rentalContract', ['contractNo'], unique=True)
    op.create_index(op.f('ix_rentalContract_partyId'), 'rentalContract', ['partyId'], unique=False)
    op.create_index(op.f('ix_rentalContract_startDate'), 'rentalContract', ['startDate'], unique=False)
    op.create_index(op.f('ix_rentalContract_status'), 'rentalContract', ['status'], unique=False)
    op.create_table('contractLine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contractId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('Item', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('returnedQty', sa.Integer(), nullable=False),
    sa.Column('ratePerUnit', sa.Float(), nullable=False),
    sa.Column('rentFrequency', sa.String(length=20), nullable=False),
    sa.Column('accruedRent', sa.Float(), nullable=False),
    sa.CheckConstraint('"ratePerUnit" >= 0', name='ck_line_rate_non_negative'),
    sa.CheckConstraint('"returnedQty" <= qty', name='ck_line_returned_not_over_qty'),
    sa.CheckConstraint('"returnedQty" >= 0', name='ck_line_returned_non_negative'),
    sa.CheckConstraint('qty > 0', name='ck_line_qty_positive'),
    sa.ForeignKeyConstraint(['contractId'], ['rentalContract.contractId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itemId'], ['t_Item.itemId'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractLine_contractId'), 'contractLine', ['contractId'], unique=False)
    op.create_index(op.f('ix_contractLine_itemId'), 'contractLine', ['itemId'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contractId', sa.Integer(), nullable=True),
    sa.Column('partyId', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paidAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['contractId'], ['rentalContract.contractId'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partyId'], ['t_party.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_contractId'), 'payment', ['contractId'], unique=False)
    op.create_index(op.f('ix_payment_paidAt'), 'payment', ['paidAt'], unique=False)
    op.create_index(op.f('ix_payment_partyId'), 'payment', ['partyId'], unique=False)
    op.create_table('returnTxn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contractId', sa.Integer(), nullable=False),
    sa.Column('lineId', sa.Integer(), nullable=True),
    sa.Column('partyId', sa.String(length=50), nullable=False),
    sa.Column('PartyName', sa.String(length=100), nullable=True),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('Item', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('returnDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('daysHeld', sa.Integer(), nullable=False),
    sa.Column('periodsCharged', sa.Integer(), nullable=False),
    sa.Column('ratePerUnit', sa.Float(), nullable=False),
    sa.Column('rentCharged', sa.Float(), nullable=False),
    sa.Column('amountPaid', sa.Float(), nullable=False),
    sa.CheckConstraint('"daysHeld" >= 0', name='ck_return_days_non_negative'),
    sa.CheckConstraint('"rentCharged" >= 0', name='ck_return_charge_non_negative'),
    sa.CheckConstraint('qty > 0', name='ck_return_qty_positive'),
    sa.ForeignKeyConstraint(['contractId'], ['rentalContract.contractId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itemId'], ['t_Item.itemId'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lineId'], ['contractLine.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partyId'], ['t_party.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returnTxn_contractId'), 'returnTxn', ['contractId'], unique=False)
    op.create_index(op.f('ix_returnTxn_itemId'), 'returnTxn', ['itemId'], unique=False)
    op.create_index(op.f('ix_returnTxn_partyId'), 'returnTxn', ['partyId'], unique=False)
    op.create_index(op.f('ix_returnTxn_returnDate'), 'returnTxn', ['returnDate'], unique=False)
    op.create_index('ix_return_contract_date', 'returnTxn', ['contractId', 'returnDate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_return_contract_date', table_name='returnTxn')
    op.drop_index(op.f('ix_returnTxn_returnDate'), table_name='returnTxn')
    op.drop_index(op.f('ix_returnTxn_partyId'), table_name='returnTxn')
    op.drop_index(op.f('ix_returnTxn_itemId'), table_name='returnTxn')
    op.drop_index(op.f('ix_returnTxn_contractId'), table_name='returnTxn')
    op.drop_table('returnTxn')
    op.drop_index(op.f('ix_payment_partyId'), table_name='payment')
    op.drop_index(op.f('ix_payment_paidAt'), table_name='payment')
    op.drop_index(op.f('ix_payment_contractId'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_contractLine_itemId'), table_name='contractLine')
    op.drop_index(op.f('ix_contractLine_contractId'), table_name='contractLine')
    op.drop_table('contractLine')
    op.drop_index(op.f('ix_rentalContract_status'), table_name='rentalContract')
    op.drop_index(op.f('ix_rentalContract_startDate'), table_name='rentalContract')
    op.drop_index(op.f('ix_rentalContract_partyId'), table_name='rentalContract')
    op.drop_index(op.f('ix_rentalContract_contractNo'), table_name='rentalContract')
    op.drop_index('ix_contract_party_date', table_name='rentalContract')
    op.drop_table('rentalContract')
    op.drop_index(op.f('ix_t_party_status'), table_name='t_party')
    op.drop_index(op.f('ix_t_party_name'), table_name='t_party')
    op.drop_index(op.f('ix_t_party_mobile'), table_name='t_party')
    op.drop_index(op.f('ix_t_party_agentId'), table_name='t_party')
    op.drop_table('t_party')
    op.drop_table('t_AvaiableStock')
    op.drop_table('RentalPrice')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_t_Item_name'), table_name='t_Item')
    op.drop_table('t_Item')
    op.drop_index(op.f('ix_t_Agents_AgentName'), table_name='t_Agents')
    op.drop_table('t_Agents')
    # ### end Alembic commands ###
